import { Routes } from '@angular/router';

export const routes: Routes = [
  { path: '', redirectTo: '/dashboard', pathMatch: 'full' },
  { path: 'dashboard', loadComponent: () => import('./components/dashboard/dashboard.component').then(m => m.DashboardComponent) },
  { path: 'companies', loadComponent: () => import('./components/companies/company-list.component').then(m => m.CompanyListComponent) },
  { path: 'companies/new', loadComponent: () => import('./components/companies/company-form.component').then(m => m.CompanyFormComponent) },
  { path: 'companies/:id', loadComponent: () => import('./components/companies/company-form.component').then(m => m.CompanyFormComponent) },
  { path: 'clients', loadComponent: () => import('./components/clients/client-list.component').then(m => m.ClientListComponent) },
  { path: 'clients/new', loadComponent: () => import('./components/clients/client-form.component').then(m => m.ClientFormComponent) },
  { path: 'clients/:id', loadComponent: () => import('./components/clients/client-form.component').then(m => m.ClientFormComponent) },
  { path: 'vehicles', loadComponent: () => import('./components/vehicles/vehicle-list.component').then(m => m.VehicleListComponent) },
  { path: 'vehicles/new', loadComponent: () => import('./components/vehicles/vehicle-form.component').then(m => m.VehicleFormComponent) },
  { path: 'vehicles/:id', loadComponent: () => import('./components/vehicles/vehicle-form.component').then(m => m.VehicleFormComponent) },
  { path: 'suppliers', loadComponent: () => import('./components/suppliers/supplier-list.component').then(m => m.SupplierListComponent) },
  { path: 'suppliers/new', loadComponent: () => import('./components/suppliers/supplier-form.component').then(m => m.SupplierFormComponent) },
  { path: 'suppliers/:id', loadComponent: () => import('./components/suppliers/supplier-form.component').then(m => m.SupplierFormComponent) },
  { path: 'categories', loadComponent: () => import('./components/categories/category-list.component').then(m => m.CategoryListComponent) },
  { path: 'categories/new', loadComponent: () => import('./components/categories/category-form.component').then(m => m.CategoryFormComponent) },
  { path: 'categories/:id', loadComponent: () => import('./components/categories/category-form.component').then(m => m.CategoryFormComponent) },
  { path: 'products', loadComponent: () => import('./components/products/product-list.component').then(m => m.ProductListComponent) },
  { path: 'products/new', loadComponent: () => import('./components/products/product-form.component').then(m => m.ProductFormComponent) },
  { path: 'products/:id', loadComponent: () => import('./components/products/product-form.component').then(m => m.ProductFormComponent) },
  { path: 'services', loadComponent: () => import('./components/services/service-list.component').then(m => m.ServiceListComponent) },
  { path: 'services/new', loadComponent: () => import('./components/services/service-form.component').then(m => m.ServiceFormComponent) },
  { path: 'services/:id', loadComponent: () => import('./components/services/service-form.component').then(m => m.ServiceFormComponent) },
  { path: 'expense-categories', loadComponent: () => import('./components/expense-categories/expense-category-list.component').then(m => m.ExpenseCategoryListComponent) },
  { path: 'expense-categories/new', loadComponent: () => import('./components/expense-categories/expense-category-form.component').then(m => m.ExpenseCategoryFormComponent) },
  { path: 'expense-categories/:id', loadComponent: () => import('./components/expense-categories/expense-category-form.component').then(m => m.ExpenseCategoryFormComponent) },
  { path: 'expenses', loadComponent: () => import('./components/expenses/expense-list.component').then(m => m.ExpenseListComponent) },
  { path: 'expenses/new', loadComponent: () => import('./components/expenses/expense-form.component').then(m => m.ExpenseFormComponent) },
  { path: 'expenses/:id', loadComponent: () => import('./components/expenses/expense-form.component').then(m => m.ExpenseFormComponent) },
  { path: 'supplier-orders', loadComponent: () => import('./components/supplier-orders/supplier-order-list.component').then(m => m.SupplierOrderListComponent) },
  { path: 'work-orders', loadComponent: () => import('./components/work-orders/work-order-list.component').then(m => m.WorkOrderListComponent) },
  { path: 'work-orders/new', loadComponent: () => import('./components/work-orders/work-order-form.component').then(m => m.WorkOrderFormComponent) },
  { path: 'work-orders/:id', loadComponent: () => import('./components/work-orders/work-order-form.component').then(m => m.WorkOrderFormComponent) },
  { path: 'invoices', loadComponent: () => import('./components/invoices/invoice-list.component').then(m => m.InvoiceListComponent) },
  { path: 'payments', loadComponent: () => import('./components/payments/payment-list.component').then(m => m.PaymentListComponent) },
  { path: 'inventory', loadComponent: () => import('./components/inventory/inventory-list.component').then(m => m.InventoryListComponent) }
];
