import { Routes } from '@angular/router';
import { authGuard, adminGuard, moduleGuard } from './guards/auth.guard';

export const routes: Routes = [
  { path: 'login', loadComponent: () => import('./components/auth/login.component').then(m => m.LoginComponent) },
  { path: 'change-password', loadComponent: () => import('./components/auth/change-password.component').then(m => m.ChangePasswordComponent), canActivate: [authGuard] },
  { path: '', redirectTo: '/dashboard', pathMatch: 'full' },
  { path: 'dashboard', loadComponent: () => import('./components/dashboard/dashboard.component').then(m => m.DashboardComponent), canActivate: [authGuard] },
  { path: 'companies', loadComponent: () => import('./components/companies/company-list.component').then(m => m.CompanyListComponent), canActivate: [authGuard], data: { module: 'CUSTOMERS' } },
  { path: 'companies/new', loadComponent: () => import('./components/companies/company-form.component').then(m => m.CompanyFormComponent), canActivate: [authGuard], data: { module: 'CUSTOMERS' } },
  { path: 'companies/:id', loadComponent: () => import('./components/companies/company-form.component').then(m => m.CompanyFormComponent), canActivate: [authGuard], data: { module: 'CUSTOMERS' } },
  { path: 'clients', loadComponent: () => import('./components/clients/client-list.component').then(m => m.ClientListComponent), canActivate: [authGuard], data: { module: 'CUSTOMERS' } },
  { path: 'clients/new', loadComponent: () => import('./components/clients/client-form.component').then(m => m.ClientFormComponent), canActivate: [authGuard], data: { module: 'CUSTOMERS' } },
  { path: 'clients/:id', loadComponent: () => import('./components/clients/client-form.component').then(m => m.ClientFormComponent), canActivate: [authGuard], data: { module: 'CUSTOMERS' } },
  { path: 'vehicles', loadComponent: () => import('./components/vehicles/vehicle-list.component').then(m => m.VehicleListComponent), canActivate: [authGuard], data: { module: 'CUSTOMERS' } },
  { path: 'vehicles/new', loadComponent: () => import('./components/vehicles/vehicle-form.component').then(m => m.VehicleFormComponent), canActivate: [authGuard], data: { module: 'CUSTOMERS' } },
  { path: 'vehicles/:id', loadComponent: () => import('./components/vehicles/vehicle-form.component').then(m => m.VehicleFormComponent), canActivate: [authGuard], data: { module: 'CUSTOMERS' } },
  { path: 'suppliers', loadComponent: () => import('./components/suppliers/supplier-list.component').then(m => m.SupplierListComponent), canActivate: [authGuard], data: { module: 'INVENTORY' } },
  { path: 'suppliers/new', loadComponent: () => import('./components/suppliers/supplier-form.component').then(m => m.SupplierFormComponent), canActivate: [authGuard], data: { module: 'INVENTORY' } },
  { path: 'suppliers/:id', loadComponent: () => import('./components/suppliers/supplier-form.component').then(m => m.SupplierFormComponent), canActivate: [authGuard], data: { module: 'INVENTORY' } },
  { path: 'categories', loadComponent: () => import('./components/categories/category-list.component').then(m => m.CategoryListComponent), canActivate: [authGuard], data: { module: 'INVENTORY' } },
  { path: 'categories/new', loadComponent: () => import('./components/categories/category-form.component').then(m => m.CategoryFormComponent), canActivate: [authGuard], data: { module: 'INVENTORY' } },
  { path: 'categories/:id', loadComponent: () => import('./components/categories/category-form.component').then(m => m.CategoryFormComponent), canActivate: [authGuard], data: { module: 'INVENTORY' } },
  { path: 'products', loadComponent: () => import('./components/products/product-list.component').then(m => m.ProductListComponent), canActivate: [authGuard], data: { module: 'INVENTORY' } },
  { path: 'products/new', loadComponent: () => import('./components/products/product-form.component').then(m => m.ProductFormComponent), canActivate: [authGuard], data: { module: 'INVENTORY' } },
  { path: 'products/:id', loadComponent: () => import('./components/products/product-form.component').then(m => m.ProductFormComponent), canActivate: [authGuard], data: { module: 'INVENTORY' } },
  { path: 'services', loadComponent: () => import('./components/services/service-list.component').then(m => m.ServiceListComponent), canActivate: [authGuard], data: { module: 'INVENTORY' } },
  { path: 'services/new', loadComponent: () => import('./components/services/service-form.component').then(m => m.ServiceFormComponent), canActivate: [authGuard], data: { module: 'INVENTORY' } },
  { path: 'services/:id', loadComponent: () => import('./components/services/service-form.component').then(m => m.ServiceFormComponent), canActivate: [authGuard], data: { module: 'INVENTORY' } },
  { path: 'expense-categories', loadComponent: () => import('./components/expense-categories/expense-category-list.component').then(m => m.ExpenseCategoryListComponent), canActivate: [authGuard], data: { module: 'FINANCE' } },
  { path: 'expense-categories/new', loadComponent: () => import('./components/expense-categories/expense-category-form.component').then(m => m.ExpenseCategoryFormComponent), canActivate: [authGuard], data: { module: 'FINANCE' } },
  { path: 'expense-categories/:id', loadComponent: () => import('./components/expense-categories/expense-category-form.component').then(m => m.ExpenseCategoryFormComponent), canActivate: [authGuard], data: { module: 'FINANCE' } },
  { path: 'expenses', loadComponent: () => import('./components/expenses/expense-list.component').then(m => m.ExpenseListComponent), canActivate: [authGuard], data: { module: 'FINANCE' } },
  { path: 'expenses/new', loadComponent: () => import('./components/expenses/expense-form.component').then(m => m.ExpenseFormComponent), canActivate: [authGuard], data: { module: 'FINANCE' } },
  { path: 'expenses/:id', loadComponent: () => import('./components/expenses/expense-form.component').then(m => m.ExpenseFormComponent), canActivate: [authGuard], data: { module: 'FINANCE' } },
  { path: 'supplier-orders', loadComponent: () => import('./components/supplier-orders/supplier-order-list.component').then(m => m.SupplierOrderListComponent), canActivate: [authGuard], data: { module: 'OPERATIONS' } },
  { path: 'work-orders', loadComponent: () => import('./components/work-orders/work-order-list.component').then(m => m.WorkOrderListComponent), canActivate: [authGuard], data: { module: 'OPERATIONS' } },
  { path: 'work-orders/new', loadComponent: () => import('./components/work-orders/work-order-form.component').then(m => m.WorkOrderFormComponent), canActivate: [authGuard], data: { module: 'OPERATIONS' } },
  { path: 'work-orders/:id', loadComponent: () => import('./components/work-orders/work-order-form.component').then(m => m.WorkOrderFormComponent), canActivate: [authGuard], data: { module: 'OPERATIONS' } },
  { path: 'invoices', loadComponent: () => import('./components/invoices/invoice-list.component').then(m => m.InvoiceListComponent), canActivate: [authGuard], data: { module: 'FINANCE' } },
  { path: 'payments', loadComponent: () => import('./components/payments/payment-list.component').then(m => m.PaymentListComponent), canActivate: [authGuard], data: { module: 'FINANCE' } },
  { path: 'inventory', loadComponent: () => import('./components/inventory/inventory-list.component').then(m => m.InventoryListComponent), canActivate: [authGuard], data: { module: 'INVENTORY' } },
  { path: 'users', loadComponent: () => import('./components/users/user-list.component').then(m => m.UserListComponent), canActivate: [adminGuard] }
];
